# Generated by Django 4.0 on 2023-11-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurances', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assure',
            old_name='address',
            new_name='addresse',
        ),
        migrations.RenameField(
            model_name='assure',
            old_name='number',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='EquivKwh',
            new_name='Mois_Equivalent',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='customer',
            new_name='assure',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='operation_date',
            new_name='date_operation',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='montant',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='meter',
            new_name='vehicule',
        ),
        migrations.RenameField(
            model_name='vehicule',
            old_name='customer',
            new_name='assure',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='SoldeKwh',
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='numero_chassis',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
