# Generated by Django 4.0 on 2023-11-30 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('assurances', '0002_rename_address_assure_addresse_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assure',
            options={'verbose_name': 'Assure', 'verbose_name_plural': 'Assures'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payement', 'verbose_name_plural': 'Payements'},
        ),
        migrations.AlterModelOptions(
            name='vehicule',
            options={'verbose_name': 'Vehicule', 'verbose_name_plural': 'Vehicules'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='Mois_Equivalent',
        ),
        migrations.AddField(
            model_name='assure',
            name='date_enr',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='assure',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='enr_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
        ),
        migrations.AddField(
            model_name='payment',
            name='mis_ajour',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='assure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assurances.assure'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_operation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='vehicule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assurances.vehicule'),
        ),
    ]
