# Generated by Django 4.0 on 2023-11-30 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assurances', '0003_alter_assure_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assure',
            name='date_enr',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='vehicule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assurances.vehicule'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='assure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assurances.assure'),
        ),
    ]
