# Generated by Django 4.1.5 on 2023-12-01 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assurances', '0004_alter_assure_date_enr_alter_payment_vehicule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assure',
            name='enr_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='date_fabrication',
            field=models.DateField(),
        ),
    ]
