# Generated by Django 3.2.15 on 2022-10-08 18:57

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompteMobileClient',
            fields=[
                ('id_cl', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phonenumber', models.CharField(max_length=30)),
                ('Solde', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id_op', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('date_operation', models.DateField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiSimilation.comptemobileclient')),
            ],
        ),
    ]
