# Generated by Django 3.2.15 on 2022-10-11 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiSimilation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='client',
        ),
        migrations.DeleteModel(
            name='CompteMobileClient',
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
    ]
