# Generated by Django 3.2.15 on 2022-10-16 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiSimilation', '0003_comptemobileclient_operation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comptemobileclient',
            old_name='Solde',
            new_name='SoldeMobile',
        ),
    ]
